### ISSUE TITLE
Things to fix

### ISSUE THREAD

**Issue by lucacasonato** [denoland/deno_doc#1]
- [x] Remove dependency on deno_core
- [x] Setup CI (copy from deno_lint)
- [ ] Remove `DocFileLoader` trait
- [x] Setup CLA
- [x] Setup Discord webhooks
- [ ] Dedupe swc_util with deno and deno_lint
- [ ] Unify method signatures on DocParser
- [ ] Node definitions should move under `src/nodes`
- [ ] Move printer back into `deno/cli`

**Comment by bartlomieju** [comment]
Superseded by #111
