### ISSUE TITLE
Confusing output when the given file does not exist

### ISSUE THREAD

**Issue by LionC** [denoland/deno_doc#109]
## Observed Behaviour

When running

    $ deno doc typoinfilename

I receive the following output (actual paths ommitted for privacy):

    The graph is missing a dependency.
        Specifier: file:///somepath/typoinfilename from file:///somepath/$deno$doc.ts

## Expected Behaviour

I would have expected a message that tells me straight that `typoinfilename` could not be found, something **like**:

    'typoinfilename' can not be found
    
    Make sure to pass a path or URL pointing to an ES module

## How to reproduce

Run

    deno doc somemissingfile

with `somemissingfile` not being a file in the current folder.

**Comment by wperron** [comment]
What OS / version of Deno are you running on? Running the repro steps on Ubuntu 21.04 gives me the correct result:
```bash
$ deno doc foobarbaz
The graph is missing a dependency.
  Specifier: file:///home/REDACTED/foobarbaz from file:///home/REDACTED/$deno$doc.ts
```

**Comment by LionC** [comment]
> What OS / version of Deno are you running on? Running the repro steps on Ubuntu 21.04 gives me the correct result:
> 
> ```bash
> 
> $ deno doc foobarbaz
> 
> The graph is missing a dependency.
> 
>   Specifier: file:///home/REDACTED/foobarbaz from file:///home/REDACTED/$deno$doc.ts
> 
> ```

Yes that is the behaviour on my side as well (see observed behaviour above) - my issue is that it is not very clear, as the problem is just a missing file / typo in a filename.

**Comment by wperron** [comment]
yes, I just realized my mistake, carry on

**Comment by kitsonk** [comment]
The behaviour was changed when `deno_graph` was integrated into `deno_doc` and then integrated into CLI, the error is now:

```
> deno doc typeinfilename
An error was returned from the loader: No such file or directory (os error 2)
```
