### ISSUE TITLE
Exported interface and class with same name only interface is documented

### ISSUE THREAD

**Issue by crowlKats** [denoland/deno_doc#15]
[in this example](https://doc.deno.land/https/raw.githubusercontent.com/denosaurs/denord/26ae2cc4c0f8c03b14d2b36eaa74b9e6d49665ed/mod.ts#ShardManager) documentation only shows the interface for `ShardManager`, but actually what is exported from the file is a `ShardManager` interface & class.

**Comment by bartlomieju** [comment]
@crowlKats could you elaborate, checking the raw file (https://raw.githubusercontent.com/denosaurs/denord/26ae2cc4c0f8c03b14d2b36eaa74b9e6d49665ed/mod.ts) shows only:
```ts
export { ShardManager } from "./src/gateway/ShardManager.ts";
export { RestClient } from "./src/rest/RestClient.ts";
```
So the output looks correct

**Comment by crowlKats** [comment]
`./src/gateway/ShardManager.ts` itself has `export interface ShardManager` & `export class ShardManager`

**Comment by bartlomieju** [comment]
Thanks for pointing this out. I guess we never thought of such case.
