### ISSUE TITLE
Supporting import maps in JS/WASM Api

### ISSUE THREAD

**Issue by andreespirela** [denoland/deno_doc#158]
Supporting import maps in JS/WASM Api

**Comment by andreespirela** [comment]
I guess it could be an implementation from `resolve` and `load`

**Comment by bartlomieju** [comment]
This will require moving implementation of import map into a separate repository (so `deno_graph` could use it). If @kitsonk doesn't have any objections I can look into doing that this week.

**Comment by kitsonk** [comment]
@bartlomieju no objections, though it does feel like we are collecting lots of crates.

**Comment by bartlomieju** [comment]
> @bartlomieju no objections, though it does feel like we are collecting lots of crates.

That's true - OTOH we had only 2 significant upgrades to `importmap.rs` since it was first added in 2019, one in 2020 and one in 2021 (to use WPT tests). I believe it shouldn't be a big deal to maintain it out of main repo and might actually help us push some of proposed import maps features forward (like resolution of nested import maps https://github.com/WICG/import-maps/issues/252).

**Comment by kitsonk** [comment]
> I believe it shouldn't be a big deal to maintain it out of main repo 

I would like `deno_graph` to (re)export it as part of the wasm API surface and clearly `deno_doc` should re-export it too.  Consider how that could be done if it sits in `denoland/deno`.

**Comment by bartlomieju** [comment]
> > I believe it shouldn't be a big deal to maintain it out of main repo
> 
> I would like `deno_graph` to (re)export it as part of the wasm API surface and clearly `deno_doc` should re-export it too. Consider how that could be done if it sits in `denoland/deno`.

The only way would be to have an `importmap` crate in `denoland/deno`, but I'm not sure if that's any better than having a dedicated repo. `deno_lint` would also consume it via `deno_graph`.

**Comment by kitsonk** [comment]
Closed in #255
