### ISSUE TITLE
Provide a way to parse modules in the DocParser

### ISSUE THREAD

**Issue by zhmushan** [denoland/deno_doc#17]
In some cases, I want to handle `reexports` manually. Could we provide a method which returns `ModuleDoc`?

**Comment by bartlomieju** [comment]
@zhmushan I'm not sure I understand, but it seems you just want to have `DocParser::parse_module` method be public. If so, I'm open to this change.

**Comment by zhmushan** [comment]
Yes, I made a pr for this
