### ISSUE TITLE
Parameter properties are ignored

### ISSUE THREAD

**Issue by LionC** [denoland/deno_doc#192]
Typescript has [parameter properties](https://www.typescriptlang.org/docs/handbook/2/classes.html#parameter-properties), but `deno_doc` ignores them. To reproduce, compare the output between running `deno doc` on this:

```typescript
class Example {
  name: string

  constructor(name: string) {
    this.name = name
  }
}
```

vs this

```typescript
class Example {
  constructor(
    public name: string
  ) {}
}
```

`deno doc` will output the `name` property for the first example but not for the second.

**Comment by kitsonk** [comment]
It looks like we are missing the accessability value on constructor params:

```json
[
  {
    "kind": "class",
    "name": "Example",
    "location": {
      "filename": "file:///Users/kitsonk/github/scratch/e.ts",
      "line": 1,
      "col": 0
    },
    "classDef": {
      "isAbstract": false,
      "constructors": [
        {
          "accessibility": null,
          "name": "constructor",
          "params": [
            {
              "kind": "identifier",
              "name": "name",
              "optional": false,
              "tsType": {
                "repr": "string",
                "kind": "keyword",
                "keyword": "string"
              }
            }
          ],
          "location": {
            "filename": "file:///Users/kitsonk/github/scratch/e.ts",
            "line": 2,
            "col": 2
          }
        }
      ],
      "properties": [],
      "indexSignatures": [],
      "methods": [],
      "extends": null,
      "implements": [],
      "typeParams": [],
      "superTypeParams": []
    }
  }
]
```

I believe they are part of the AST.  That being said, "hoisting" that to a parameter might not make sense, but should be made visible in the documentation, something like this:

```

class Example

  constructor(public name: string)


```

**Comment by LionC** [comment]
I spent some time looking into how to fix this yesterday and it seems that the`TSParamProp` struct has all data that we need and it is already being matched anyways, so we just need to add into that conditional branch.

> I believe they are part of the AST.  That being said, "hoisting" that to a parameter might not make sense, but should be made visible in the documentation, something like this:
> 
> 
> 
> ```
> 
> 
> 
> class Example
> 
> 
> 
>   constructor(public name: string)
> 
> 
> 
> 
> 
> ```

I am not sure if I jnderstand you correctly. I think my two examples from the issue should result in the exact same docs. Using a parameter prop is an implementation detail in my mind, in the end it is a normal class property and a normal constructor argument. I would not expect refactoring that later on to a mormal prop and a normal parameter to cause doc changes.

I would be happy to try to put a PR up for that - I have not contributed to the Rust part of the project yet, would be s good opportunity to get into the architecture and project structure there :-)

**Comment by kitsonk** [comment]
> I am not sure if I understand you correctly. I think my two examples from the issue should result in the exact same docs. Using a parameter prop is an implementation detail in my mind, in the end it is a normal class property and a normal constructor argument.

But we don't "restructure" the interpreted AST.  For example getters and setters are listed as methods in the doc nodes, though they effectively operate as properties.  It is up to the documentation "printer" to interpret how they manifest themselves.  So the accessibility parameter should appear in the constructor parameters, and that is all.  It is up to the doc printer to represent that in a meaningful way.
