### ISSUE TITLE
All untagged paragraphs following a tag are ignored

### ISSUE THREAD

**Issue by SeparateRecords** [denoland/deno_doc#194]
Paragraphs following a tag will be ignored if they're untagged. This is common (leading `@deprecated`, etc)

```ts
/**
 * Paragraph 1
 *
 * @deprecated Paragraph 2
 *
 * Paragraph 3
 *
 * @param paramagraph 4
 */
export let a;
```
Paragraph 3 gets eaten:
```json
[
  {
    "kind": "variable",
    "name": "a",
    "location": {
      "filename": "file:///Users/robert/Workspaces/github.com/denoland/deno_doc/repro.ts",
      "line": 10,
      "col": 0
    },
    "jsDoc": {
      "doc": "Paragraph 1\n",
      "tags": [
        {
          "kind": "deprecated",
          "doc": "Paragraph 2"
        },
        {
          "kind": "param",
          "name": "paramagraph",
          "doc": "4"
        }
      ]
    },
    "variableDef": {
      "tsType": null,
      "kind": "let"
    }
  }
]
```
`jsDoc.doc` should be `"Paragraph 1\n\nParagraph 3\n"`

<details>
<summary>Example from builtins (Deno.copy)</summary>

```js
  /**
   * @deprecated Use `copy` from https://deno.land/std/io/util.ts instead.
   * `Deno.copy` will be removed in Deno 2.0.
   *
   * Copies from `src` to `dst` until either EOF (`null`) is read from `src` or
   * an error occurs. It resolves to the number of bytes copied or rejects with
   * the first error encountered while copying.
   *
   * ```ts
   * const source = await Deno.open("my_file.txt");
   * const bytesCopied1 = await Deno.copy(source, Deno.stdout);
   * const destination = await Deno.create("my_file_2.txt");
   * const bytesCopied2 = await Deno.copy(source, destination);
   * ```
   *
   * @param src The source to copy from
   * @param dst The destination to copy to
   * @param options Can be used to tune size of the buffer. Default size is 32kB
   */
```
Becomes this output. Notice the missing second paragraph and example - `jsDoc` should have a `doc` property.
```json
"kind": "function",
"name": "copy",
"location": {
  "filename": "deno://lib.deno.d.ts",
  "line": 441,
  "col": 2
},
"jsDoc": {
  "tags": [
    {
      "kind": "deprecated",
      "doc": "Use `copy` from https://deno.land/std/io/util.ts instead."
    },
    {
      "kind": "param",
      "name": "src",
      "doc": "The source to copy from"
    },
    {
      "kind": "param",
      "name": "dst",
      "doc": "The destination to copy to"
    },
    {
      "kind": "param",
      "name": "options",
      "doc": "Can be used to tune size of the buffer. Default size is 32kB"
    }
  ]
},
```

</details>

Found this while fixing denoland/doc_website#252 - this blocks upgrading the doc website's Deno version.

**Comment by SeparateRecords** [comment]
Fixed this in a local copy, I'll have a PR with tests up soon. Bug was introduced in #144, problem was [src/js_doc.rs#L45](https://github.com/denoland/deno_doc/blob/bb376c6497bd385f87ec726a60cbd7fc14ae60a3/src/js_doc.rs#L45) - once is_tag is true, it's never set to false, so every line is pushed to the current_tag vec instead of doc_lines

**Comment by kitsonk** [comment]
Basically there is ambiguity here.  With block comments like this, how do we determine that "Paragraph 3" isn't associated with the `@deprecated` tag?  Often, especially with `@param` there are multiple line comment blocks.  So technically it should be:

```json
[
  {
    "kind": "variable",
    "name": "a",
    "location": {
      "filename": "file:///Users/robert/Workspaces/github.com/denoland/deno_doc/repro.ts",
      "line": 10,
      "col": 0
    },
    "jsDoc": {
      "doc": "Paragraph 1\n",
      "tags": [
        {
          "kind": "deprecated",
          "doc": "Paragraph 2\n\nParagraph 3"
        },
        {
          "kind": "param",
          "name": "paramagraph",
          "doc": "4"
        }
      ]
    },
    "variableDef": {
      "tsType": null,
      "kind": "let"
    }
  }
]
```

You can see this in something like vscode:

```ts
/**
 * Paragraph 1
 *
 * @deprecated Paragraph 2
 *
 * Paragraph 3
 *
 * @param param Paragraph 4
 * Paragraph 5
 * 
 * Paragraph 6
 */
export function a(param: string) {}


a("glow");
```

It provides the entire doc block when hovering over the function, including all the tags:

![test_ts_—_deno](https://user-images.githubusercontent.com/1282577/135561811-a16c3e54-940a-4aa1-b951-9637425c8364.png)

But associates anything after the block tag with the block tag, so hovering over the first param provides this:

![test_ts_—_deno](https://user-images.githubusercontent.com/1282577/135562000-53a5007b-199f-46a3-8649-50f132910250.png)

**Comment by kitsonk** [comment]
> Fixed this in a local copy, I'll have a PR with tests up soon. Bug was introduced in #144, problem was [src/js_doc.rs#L45](https://github.com/denoland/deno_doc/blob/bb376c6497bd385f87ec726a60cbd7fc14ae60a3/src/js_doc.rs#L45) - once is_tag is true, it's never set to false, so every line is pushed to the current_tag vec instead of doc_lines

As I have stated though, the correct fix is to associate "Paragraph 3" with the `@deprecated` tag.

**Comment by SeparateRecords** [comment]
Ahh I see. In that case the current behaviour in `From<String> for JsDoc` is indeed correct since everything after a tag is associated with that tag.

Correct me if I'm wrong, but I think the bug is in the other regexes since they match `.`, which is any char except \r or \n, instead of `[\s\S]`. Dot causes only the first line to be matched.

I'll start on a fix for that.

**Comment by kitsonk** [comment]
I think we may want to use the `(?s)`/dotall flag.
