### ISSUE TITLE
An unexpected error on a module but not on a mod.ts that re-exports it

### ISSUE THREAD

**Issue by KyleJune** [denoland/deno_doc#209]
When I tried viewing the deno docs for a module of mine, I get an unexpected error.

https://doc.deno.land/https/deno.land/x/collections@0.11.2/trees/rb_tree.ts

![image](https://user-images.githubusercontent.com/3241653/141666228-0746810a-5404-4e67-8946-e5c81d83eadd.png)

If I look at the deno docs for the mod.ts file that re-exports it, it shows docs correctly for the class exported from trees/rb_tree.ts.

https://doc.deno.land/https/deno.land/x/collections@0.11.2/mod.ts#RBTree

![image](https://user-images.githubusercontent.com/3241653/141666307-5601dcd1-202c-48dd-978d-6dfc5c2d8059.png)

When I run lint and format on rb_tree.ts, it doesn't show there being any issues.

**Comment by bartlomieju** [comment]
CC @lucacasonato

**Comment by KyleJune** [comment]
I believe it's related to the class extending a class that it imports but does not re-export. The mod.ts exports both the base RBTree and BSTree while the rb_tree.ts file only exports the RBTree. It doesn't appear to have an issue showing docs when some of the other classes are not exported, for example BSNode is used internally and not exported, yet the mod.ts is still able to show docs for RBTree. I think the docs should be able to work even though RBTree does not re-export BSTree.

**Comment by kitsonk** [comment]
This appears to no longer be an issue with the [new doc website](https://doc.deno.land/https://deno.land/x/collections@0.11.2/trees/rb_tree.ts/~/RBTree) (and wasn't an issue with deno_doc in the first place, just the doc website).
