### ISSUE TITLE
missing `@param`, `@returns` description

### ISSUE THREAD

**Issue by cs09g** [denoland/deno_doc#214]
Just tried as described [here](https://deno.land/manual/tools/documentation_generator).

code:
```typescript
/**
 * Adds x and y.
 * @param {number} x
 * @param {number} y
 * @returns {number} Sum of x and y
 */
 export function add(x: number, y: number): number {
  return x + y;
}
```

result:
```
function add(x: number, y: number): number
  Adds x and y.
```

deno --version
```
deno 1.16.3 (release, x86_64-apple-darwin)
v8 9.7.106.5
typescript 4.4.2
```

Could you check if there's some issue with the code or document?

**Comment by kitsonk** [comment]
There was a change to how tags are parsed and are no longer being printed out. Sadly we didn't have the example in the docs as a test case, so the regression was not caught.
