### ISSUE TITLE
Add ability to view Deno runtime docs for prior versions

### ISSUE THREAD

**Issue by jsejcksn** [denoland/deno_doc#215]
At https://doc.deno.land/builtin/stable, I can see the runtime type docs for Deno's builtin APIs. This is great if I'm working with the latest stable version of Deno. However, if I need to reference a prior release version's docs, I don't see a way to do that **in a web browser**.

Is there a URL pattern I can use to generate docs for a prior release (e.g. v`1.6.3`)? If so, I wasn't able to discover it, and I think it would help to include this information in the docs website (or even better: include a `<select>` element with all of the release versions like on `deno.land/std`). If not, please consider this a feature request.

**Comment by sno2** [comment]
You can go to `https://doc.deno.land/builtin/VERSION` to get version data for specific deno versions.

- Deno v1.0.0 `Crypto` Interface: https://doc.deno.land/builtin/v1.0.0#Crypto

- Deno v1.16 `Crypto` Interface: https://doc.deno.land/builtin/v1.16.0#Crypto

**Comment by jsejcksn** [comment]
> You can go to `https://doc.deno.land/builtin/VERSION` to get version data for specific deno versions.

Thanks @sno2. How did you discover that URL pattern?

**Comment by bartlomieju** [comment]
@jsejcksn doc website is currently undergoing major rework by @kitsonk and we should provide a version selector there. Expect announcement in the coming weeks.

**Comment by jsejcksn** [comment]
Now that the rework is live, it seems like the patterns that @sno2 [listed](https://github.com/denoland/deno_doc/issues/215#issuecomment-983142478) are no longer valid. I can see

```
Version
latest
```

on the left sidebar, but there doesn't appear to be any interaction available. Is there a new pattern I can use with the updated site?

**Comment by kitsonk** [comment]
As mentioned in denoland/docland#47, the ability is there, just not documented. (E.g. https://doc.deno.land/deno/stable@v1.16.0) it just isn't documented and the other issue will track that.
