### ISSUE TITLE
Request docs as JSON

### ISSUE THREAD

**Issue by sgwilym** [denoland/deno_doc#237]
It'd be useful to be able to request docs from https://doc.deno.land/ as JSON, just as they would be returned from `deno doc --json`.

My use-case is that I'd like to display docs on my own website (which is not written using Deno).

**Comment by lucacasonato** [comment]
If you need something right now, it would be super easy to make an API yourself on Deno Deploy. See an example here:

Playground: https://dash.deno.com/playground/deno-doc-api
Demo: https://deno-doc-api.deno.dev?entrypoint=https://deno.land/std@0.120.0/http/server.ts

**Comment by kitsonk** [comment]
Both the CLI and the JavaScript/WASM interface to `deno_doc` provide this capability.  Adding directly to `doc.deno.land` doesn't specifically make sense.

The example linked to is the right way to go about it.

Closing as no further action needed.
