### ISSUE TITLE
deno doc failed with empty result?

### ISSUE THREAD

**Issue by masx200** [denoland/deno_doc#251]
![捕获 JPG5555555](https://user-images.githubusercontent.com/34191203/168007044-96e3275f-9bce-43b5-b167-72d5ee5f4fc7.JPG)

deno doc failed with empty result?

https://doc.deno.land/https://deno.land/std@0.138.0/http/server.ts

**Comment by kt3k** [comment]
@masx200 Thanks for reporting. The issue is tracked in https://github.com/denoland/docland/issues/148

(Note: this repository is about `deno doc` feature, doc.deno.land (the website) issues are tracked in https://github.com/denoland/docland )

**Comment by kt3k** [comment]
Should be fixed now!
