### ISSUE TITLE
Deno doc shouldn't include the implementation signature of functions and methods

### ISSUE THREAD

**Issue by dsherret** [denoland/deno_doc#259]
Given a method or function that looks like the following:

```ts
// example.ts
export function env(items: Record<string, string | undefined>): void;
export function env(name: string, value: string | undefined): void;
export function env(nameOrItems: string | Record<string, string | undefined>, value?: string) {
}
```

Running:

```
deno doc example.ts
```

Outputs:

```
> deno doc example.ts       
Defined in file:///V:/dax/example.ts:1:0

function env(items: Record<string, string | undefined>): void

Defined in file:///V:/dax/example.ts:2:0

function env(name: string, value: string | undefined): void

Defined in file:///V:/dax/example.ts:3:0

function env(nameOrItems: string | Record<string, string | undefined>, value?: string)
```

This shouldn't happen because the implementation signature is an implementation detail that the consumer should be concerned about. For example, TS's language server does not display the implementation signature:

![image](https://user-images.githubusercontent.com/1609021/179370743-50aadbf0-c940-4aac-ade3-087feec11eae.png)

**Comment by kitsonk** [comment]
I disagree... `deno_doc` should return all the doc nodes.  It is up to the displayer to determine what is meaningful to display.  Anything else would be a "lie".

That only potential change is the function node would indicate if the function/method contains a body.  Then clients could determine what to display.

Ref: denoland/docland#122

**Comment by dsherret** [comment]
I disagree because the implementation signature is an implementation concern.

**Comment by kitsonk** [comment]
This would require the walker to keep state with functions and overloads.  That is not what it is meant to do.  It is the "printer" that can determine what is appropriate and not appropriate to print.

**Comment by dsherret** [comment]
Couldn’t we just look at the previous node without maintaining any state? Also, is there a purpose to returning back the implementation signature?

**Comment by kitsonk** [comment]
> Couldn’t we just look at the previous node without maintaining any state?

The "previous node" is keeping state. 😕 

> Also, is there a purpose to returning back the implementation signature?

99% of the time there is only the implementation signature.  In situations where a printer want to link to (or display) the implementation, they need the doc node.  I agree currently there is no way to determine an overload versus an implementation, and that is what we should fix.  Then printers can determine what is most meaningful give a specific context.

**Comment by dsherret** [comment]
> The "previous node" is keeping state. 😕

You can just look at what the previous node is. I opened this PR quickly to demonstrate it https://github.com/denoland/deno_doc/pull/261

swc's API for dealing with nodes is very verbose, but that could be cleaned up and made to look nice. It seems like we should exclude it at the source. Then the rest of the doc code doesn't need to worry about dealing with an internal aspect of the code.

**Comment by kitsonk** [comment]
Just taking a look at this to... I am going to raise a PR for `has_body`.  In looking at that, the problem is that if there are overloads and decorators, the decorators go against the implementation.  So if we just dropped implementation, we would drop decorators.  If we didn't drop the definition if there were decorators, then we run into the same problem.

So again, I am pretty sure the best thing to do in the doc nodes is represent the code as it is written and leave it up to the printers to determine the best way to display this.

**Comment by dsherret** [comment]
Oh yeah, I forgot about decorators. That makes a lot of sense to me! I will review that PR probably tomorrow.
