### ISSUE TITLE
Add support for "typeof" inference

### ISSUE THREAD

**Issue by masx200** [denoland/deno_doc#272]
No typescript type inference??

https://deno.land/x/masx200_cloudflare_api_dns_record_zone@1.0.0/NS-Record.ts

https://doc.deno.land/https://deno.land/x/masx200_cloudflare_api_dns_record_zone@1.0.0/mod.ts/~/NSRecord

https://www.typescriptlang.org/zh/play?#code/KYDwDg9gTgLgBDAnmYcByBlASsAxtAEzgF4FlgIAzOAOwGcB9KPQgbgCh9756mWoipAN7s4YuACIAlgQkAuSQGYA7ACZgANmUBOAKwAWAAyrdwQwCMAhhsu2NBXQA4N57WfO7tEgDSjxEpBR5SUwJOEs6OC46GF9xSRpLAFtgYIlQZLAAG2AAOnwknz8xCS4YYBoYNPoARlyMpOy8gqL4iTAoCBApS3Mc4JgoAFdgOP8OrqlgWQVKSyy6UeLJGBgs4MUNQ0MxkqyIXABraeC5haW2gC8IGmAGGTTjRWAaw11KfTxgSkdLAm1cJZFDVLI4VKoCIZcIpdIpWv5rrcGIkUmkGk18hBCrtJLhmJZygQGDc0qpDDV9ABacnUmoAFTecjJcm2uRqqkU+l0AC14SUkhACFJKFMiSSFBIyRTabSGbomYYWYY2RyubycRICATLMEhABfDUpGA6hQieJtSxDGAQBh-AgnBSDEY4tp0CBDKC4VISjpSJKWKCIPlwA3sPWsIA

input

```ts
export type NSRecord = typeof ns_record;
const ns_record = {
    "id": "372e67954025e0ba6aaa6d586b9e0b59",
    "type": "NS" as const,
    "name": "example.com",
    "content": "ns1.example.com",
    "proxiable": true,
    "proxied": false,
    "ttl": 3600,
    "locked": false,
    "zone_id": "023e105f4ecef8ad9ca31a8372d0c353",
    "zone_name": "example.com",
    "created_on": "2014-01-01T05:20:00.12345Z",
    "modified_on": "2014-01-01T05:20:00.12345Z",
    "data": {},
    "meta": {
        "auto_added": true,
        "source": "primary",
    },
};

```
output expected
```ts
export declare type NSRecord = typeof ns_record;
declare const ns_record: {
    id: string;
    type: "NS";
    name: string;
    content: string;
    proxiable: boolean;
    proxied: boolean;
    ttl: number;
    locked: boolean;
    zone_id: string;
    zone_name: string;
    created_on: string;
    modified_on: string;
    data: {};
    meta: {
        auto_added: boolean;
        source: string;
    };
};
export {};
```

<img width="960" alt="image" src="https://user-images.githubusercontent.com/34191203/173227093-601dd3d8-2786-4e72-8320-96d072036aac.png">

**Comment by kitsonk** [comment]
Issue #92 covers inferring types from object literals, but then being able to link from a typeof to an inferred type would need to be added to make this complete.
