### ISSUE TITLE
Destructured export assignment not supported

### ISSUE THREAD

**Issue by kitsonk** [denoland/deno_doc#274]
Destructured assignment not supported: https://deno.land/x/base64@v0.2.1/mod.ts?code

```ts
export const { byteLength, toUint8Array, fromUint8Array } = init(
  lookup,
  revLookup,
);
```

**Comment by kitsonk** [comment]
Ok, I took a look at this and had a stab at it, but it isn't a quick change, as the assumption was made that a variable declaration statement would only have one name associated with it.  There is a TODO there noting this is a wrong assumption, but changing that causes refactoring all the way up the chain, and this needs a deeper re-working.

**Comment by crowlKats** [comment]
Closing as this works now.
