### ISSUE TITLE
Not compatible with commonjs export?

### ISSUE THREAD

**Issue by masx200** [denoland/deno_doc#288]
Not compatible with commonjs export?

https://doc.deno.land/https://unpkg.com/@masx200/binary-search-bounds@2.0.5/search-bounds.d.ts

https://unpkg.com/@masx200/binary-search-bounds@2.0.5/search-bounds.d.ts

Can't see any type?

**Comment by kitsonk** [comment]
Correct, Deno as a whole is incompatible with `export =` within an ES Module.  It can consume the types in the editor and type check ok, but it can't support exporting, as `export =` is fundamentally incompatible with ES Module specification.  It is a "bodge" in TypeScript type definitions to support describing CommonJS modules.
