### ISSUE TITLE
support `@throws` JSDoc tag

### ISSUE THREAD

**Issue by TomokiMiyauci** [denoland/deno_doc#299]
Since TypeScript does not currently support the throw signature, the `@throws` tag in JSDoc is the only documentation that indicates throwing an error.

https://jsdoc.app/tags-throws.html

**Comment by iuioiua** [comment]
@crowlKats, is this supposed to be supported? It doesn't seem to be working using `deno doc` and in JSR ([page](https://jsr.io/@std/assert/doc/~/assertNever) and [source](https://jsr.io/@std/assert/1.0.3/never.ts#L95)).
