### ISSUE TITLE
Docs don't display for global functions

### ISSUE THREAD

**Issue by Ragzouken** [denoland/deno_doc#31]
The docstrings definitely exist, and display fine in e.g vscode, but the autogenerated docs don't include them for some reason.

![image](https://user-images.githubusercontent.com/527158/93715055-be836080-fb5e-11ea-8751-8817bf34f1e4.png)

**Comment by SyrupThinker** [comment]
Caused by https://github.com/swc-project/swc/issues/843.
Assuming well formatted source code, reducing the span's start value by 8 fixes the issue:

![image](https://user-images.githubusercontent.com/7753242/102652586-2c472480-416e-11eb-89c3-aaed28b4569c.png)

Of course this is not a good solution.
