### ISSUE TITLE
Doc should infer simple TS types

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno_doc#33]
`no-inferrable-types` lint rule tells to not use following types:
- `string`
- `symbol`
- `RegExp`
- `number`
- `boolean`
- `bigint`

But when using `deno doc` type is not specified. 
![unknown](https://user-images.githubusercontent.com/13602871/95016155-703b8a80-0651-11eb-894f-b8db8a3866ee.png)

Doc generator should be able to infer those types.

CC @SyrupThinker

**Comment by uki00a** [comment]
I'll try to work on this.
