### ISSUE TITLE
Releases broken since version 0.60.0

### ISSUE THREAD

**Issue by benStre** [denoland/deno_doc#333]
The releases available at https://deno.land/x/deno_doc are not working correctly since version 0.60.0.

The files in the additional releases [deno/0.60.0](https://deno.land/x/deno_doc@deno%2F0.60.0) and [deno/0.61.0](https://deno.land/x/deno_doc@deno%2F0.61.0) that seem to be generated from the `deno_registry` branch, contain an `Access Denied` error instead of the code.

I am not sure if the `deno/x.xx.x` releases are created intentionally, but the other releases ([0.60.0](https://deno.land/x/deno_doc@0.60.0), [0.61.0](https://deno.land/x/deno_doc@0.61.0)) are also not usable, because the file [js/deno_doc.generated.js](https://deno.land/x/deno_doc@0.60.0/js/deno_doc.generated.js) (required in [js/mod.ts](https://deno.land/x/deno_doc@0.60.0/js/mod.ts)) is missing.

**Comment by dsherret** [comment]
Sorry, I forgot to add a webhook prefix. It's fixed now in 0.61.1
