### ISSUE TITLE
Implement tags

### ISSUE THREAD

**Issue by crowlKats** [denoland/deno_doc#372]
Like
<img width="260" alt="Screenshot 2023-10-31 at 13 16 19" src="https://github.com/denoland/deno_doc/assets/13135287/0626c6e9-4489-40d3-a035-fdc089f22364">
<img width="254" alt="Screenshot 2023-10-31 at 13 17 05" src="https://github.com/denoland/deno_doc/assets/13135287/b856045c-0ce7-488d-a31c-d5062ea34465">

**Comment by bartlomieju** [comment]
Is there any blocker to handling this besides creating appropriate components/templates?

**Comment by crowlKats** [comment]
nope

**Comment by crowlKats** [comment]
Closed by #444
