### ISSUE TITLE
Make $ deno doc --html read/resolve .js imports from .ts files if .js files dont exist

### ISSUE THREAD

**Issue by izelnakri** [denoland/deno_doc#389]
Currently I have one npm package where I declare `.ts` internal file imports as `.js` due to a sad compatibility benefit I get here: https://github.com/izelnakri/memoria/blob/main/packages/%40memoria/model/src/index.ts#L1

When I compile this project with `tsc` tsc can resolve and compile dependencies to a `.js` project distribution when project path is given. However I miss this feature currently given how new `$ deno doc --html` is, I think the command should resolve the `.js` files from `.ts` if `.js` doesnt exist because it seems this is what typescript team suggests and kind of implements internally.

## Steps to reproduce

This should pass:

```bash
deno doc --html --name="@memoria/model" ./index.js
```

**Comment by crowlKats** [comment]
Deno does not behave like you are asking, and wont, and deno_doc follows the same logic and rules, so we won't change this
