### ISSUE TITLE
Generates incorrect type assignment

### ISSUE THREAD

**Issue by ChuckJonas** [denoland/deno_doc#395]
I recently got tripped up by [some generated documentation](https://deno.land/x/openai@v4.16.1/mod.ts?s=default.ChatCompletion) on the deno package site  (which I assume is generated by this library?).

<img width="923" alt="default_ChatCompletion____mod_ts___openai_v4_16_1___Deno" src="https://github.com/denoland/deno_doc/assets/5217568/a842443e-e166-47a4-84c3-7eb8f4f0c612">

Deno doesn't like the `default` in the import (guessing because it's a keyword) and it's attempting to assign the type to a `const`?

https://codesandbox.io/p/sandbox/nice-easley-7dt7y4?file=%2Findex.ts%3A2%2C36

**Comment by bartlomieju** [comment]
@dsherret could you take a look at this?

**Comment by crowlKats** [comment]
Closing as this was fixed on JSR; we don't actively work on the rendering logic that /x/ uses as that is a legacy implementation. hopefully at some point soon we can update /x/ to use the same logic
