### ISSUE TITLE
Consider providing the ability to color objects such as "InterfacePropertyDef" externally

### ISSUE THREAD

**Issue by zhmushan** [denoland/deno_doc#40]
At present, we can only use `DocPrinter` to decide if it should colorize or not. But when `deno_doc` is used as a crate, we may not always want to print an entire `DocNode` object. But if we don't call `colors::enable`, no colors will be displayed.

related: https://github.com/denoland/deno_doc/pull/38

**Comment by bartlomieju** [comment]
@zhmushan that would require completely rewrite of printer so it can format any struct available in the crate. I'm happy to take contributions but it's something we won't be working on in the foreseeable future.

**Comment by bartlomieju** [comment]
I'm gonna close this issue for now as there's not much interest in it and it would require significant engineering effort.
