### ISSUE TITLE
support linking to modules & symbols via `@link`

### ISSUE THREAD

**Issue by crowlKats** [denoland/deno_doc#512]
as described in https://jsdoc.app/tags-module

a way to get a shortpath from a string that checks its a valid shortpath in this context is necessary.

**Comment by nberlette** [comment]
It would also be great to support the `@see` tag, which often times include a `@link` tag within them.

The linking is probably going to be the trickiest part. IIRC the VSCode team had quite a challenge with the contextual linking for their implementation, but theirs is a bit more robust than I'd expect deno doc's would need to be (e.g. linking to parameters by identifier only from an outer JSDoc comemnt).

**Comment by crowlKats** [comment]
@nberlette #489 for `@see`

**Comment by crowlKats** [comment]
Closing as this was achieved in #586
