### ISSUE TITLE
Use module name from `@module` tag

### ISSUE THREAD

**Issue by MarkTiedemann** [denoland/deno_doc#518]
Currently, `deno doc --html` requires the module name as an argument.

```
> deno doc --html mod.ts
error: the following required arguments were not provided:
  --name=<name>
```
I think the name could be optional if the module provides the name via JSDoc [`@module`](https://jsdoc.app/tags-module).

**Comment by crowlKats** [comment]
We are now using the module name for generating the symbol used in usage blocks for files
