### ISSUE TITLE
@internal JSDoc tag

### ISSUE THREAD

**Issue by mary-ext** [denoland/deno_doc#522]
TypeScript has an option for stripping away internal-use declarations, `stripInternals`. It removes exported variables, public fields that are marked with `@internal` in the doc comments.

Useful in two cases:
- The need to expose variables, functions for testing, but otherwise undocumented/not meant for public usage
- Where private fields in classes aren't a choice (need access from outside) and alternatives like WeakMap or declaring a getter function inside a static block seem a little too much.

```ts
class Box {
  /** @internal */
  _private: string = 'private string';
}

const box = new Box();
// we can access it, but it won't be documented at all, etc
box._private;
```

---

filed as per this [Discord message](https://discord.com/channels/684898665143206084/1203185670508515399/1216286848465502208), but perhaps it needs a little more than just on the documentation side? (e.g. JSR needs to strip it too for npm usage, Deno needs to ignore it when it's in an external dependency, etc.)

**Comment by crowlKats** [comment]
@mary-ext jsdoc specifies an `@ignore` tag; would that work for you as well?

**Comment by crowlKats** [comment]
@mary-ext we have decided with the following:
`@ignore` is the way to go for what you want to achieve, and `@internal` will be used in a different manner: it will allow for excluding symbols from overviews and have said symbol be only reachable through a reference link by another symbol (this same behaviour is now implemented for non-exported symbols that are referenced by exported symbols).

**Comment by mary-ext** [comment]
Sounds good!

**Comment by crowlKats** [comment]
Closing this issue has we decided on the behaviour which has been implemented
