### ISSUE TITLE
module jsdoc is not detect when a file have a hashbang

### ISSUE THREAD

**Issue by sigmaSd** [denoland/deno_doc#524]
a.ts

```ts
#!/usr/bin/env -S deno run // removing this line makes deno doc work again
/**
Hello
@module
*/
```

```
deno doc a.ts # no output
```

removing the hashbang makes the deno doc command work

**Comment by sigmaSd** [comment]
I think its because the start function doesn't take the hashbang into account

https://docs.rs/deno_ast/1.0.1/src/deno_ast/parsed_source.rs.html#123

**Comment by crowlKats** [comment]
This was adressed in #605
