### ISSUE TITLE
JSX inside of code blocks is rendered in docs

### ISSUE THREAD

**Issue by lucacasonato** [denoland/deno_doc#545]
```ts
/**
 * ```tsx
 * export default definePage<typeof handler>(({ data }) => {
 *   return <h1>{data.message}</h1>;
 * });
 * ```
 */
export function foo() {}
```

Results in something like this in the docs:

<img width="880" alt="Screenshot 2024-04-15 at 13 26 41" src="https://github.com/denoland/deno_doc/assets/7829205/03492e0c-77f4-4f4d-90bc-1714889f83cd">

This is with `deno doc --html` on Deno 1.42.1

**Comment by crowlKats** [comment]
Closing as fixed in #554
