### ISSUE TITLE
(Deno doc) jsDoc is not being included for declared functions

### ISSUE THREAD

**Issue by cknight** [denoland/deno_doc#7]
`Deno doc` is not including jsDoc in it's output for declared functions.  This is most obvious with the lack of any jsdoc showing for the functions at the top of https://doc.deno.land/https/github.com/denoland/deno/releases/latest/download/lib.deno.d.ts.  

To take one specific example, in `lib.deno.shared_global.ts`, `setTimeout` is declared as:

```
/** Sets a timer which executes a function once after the timer expires. Returns
 * an id which may be used to cancel the timeout.
 *
 *     setTimeout(() => { console.log('hello'); }, 500);
 */
declare function setTimeout(...)
```
but the output of `deno doc --json cli/js/lib.deno.ns.d.ts`  has null `jsDoc`:
```
  {
    "kind": "function",
    "name": "setTimeout",
    "location": {
      "filename": "file:///home/chris/dev/deno/cli/js/lib.deno.shared_globals.d.ts",
      "line": 182,
      "col": 8
    },
    "jsDoc": null,
    ...
```

**Comment by crowlKats** [comment]
Closing as this has since been fixed
