### ISSUE TITLE
Add API to generate docs for AST instead of source code

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno_doc#74]
For the purpose of denoland/deno#8641 we should have additional APIs on `DocParser` struct that allows to pass already parsed AST instead of source code.

Current API:
https://github.com/denoland/deno_doc/blob/c2f34cadcba0bf88637802eb78634ca82cbbae4a/src/parser.rs#L81-L101

Proposed API:
```rust
  pub fn parse_ast(
    &self,
    file_name: &str,
    ast: &swc_ecmascript::ast::Module,
  ) -> Result<ModuleDoc, DocError>
```

**Comment by chansuke** [comment]
I'd like to have a try on this.

**Comment by kitsonk** [comment]
This was resolved by using `deno_ast` thanks to @dsherret.
