### ISSUE TITLE
Deno doc should pull JSDoc along with type definition

### ISSUE THREAD

**Issue by Soremwar** [denoland/deno_doc#8]
While dealing with type documentation I noticed this behavior.
```javascript
//mod.js
// @deno-types="./mod.d.ts"
export function returnAsNumber(str) {
  return Number(str);
}
```
```typescript
//mod.d.ts
/**
 * This function receives a string and returns its numeric value
 */
export function returnAsnumber(str: string): number;
```
Current behavior on running `deno doc mod.js` is:
```log
function returnAsNumber(str)
```
Expected (hopeful :P) behavior on running `deno doc mod.js` should be something like:

```log
function returnAsNumber(str: string): number
  This function receives a string and returns its numeric value
```

As referenced in denoland/deno_doc#4 I would think this is in the mindset of the team as well?

**Comment by kitsonk** [comment]
This is the not the "right" way of specify [types for a JavaScript file](https://deno.land/manual@v1.13.2/typescript/types#using-the-triple-slash-reference-directive).

Doing the following in **mod.js**:

```js
/// <reference types="./mod.d.ts" />

export function returnAsNumber(str) {
  return Number(str);
}
```

Results in the following output:

```
> deno doc mod.js
Defined in file:///Users/kitsonk/github/scratch/mod.d.ts:4:0

function returnAsNumber(str: string): number
  This function receives a string and returns its numeric value

```
