### ISSUE TITLE
Feature Request: add capability to suppress documentation

### ISSUE THREAD

**Issue by QHGDerek** [denoland/deno_doc#90]
Example:
https://doc.deno.land/https/deno.land/x/playfab_sdk/support/runtime.ts#SecurityOptions

I have a type called SecurityOptions which is an OR of SecretKey | SessionTicket | EntityToken types. I'm attempting to create a "Oneof" pattern here, where the caller would set 1 of 3 possible keys, but no more than 1. The strategy to do this ends up defining extra fields that I'd like to exclude from my documentation to reduce confusion.

I'd propose some sort of suppression capability in deno_doc. There's prior art in JSDoc to support:
https://jsdoc.app/tags-ignore.html

**Comment by crowlKats** [comment]
Closing as the ignore tag is supported
