### ISSUE TITLE
`deno doc` doesn't infer types from object literal

### ISSUE THREAD

**Issue by uki00a** [denoland/deno_doc#92]
## Example

https://deno.land/x/redis@v0.21.0/protocol/reply.ts contains the following definition:

```typescript
export const replyTypes = {
  Integer: "integer",
  SimpleString: "simple string",
  Array: "array",
  BulkString: "bulk string",
} as const;
```

`deno doc` generates the following output for the above file:

```shell
$ deno doc https://deno.land/x/redis@v0.21.0/protocol/reply.ts replyTypes

Defined in https://deno.land/x/redis@v0.21.0/protocol/reply.ts:12:0

const replyTypes
```

I think `deno doc` should output type of the `replyTypes` variable, but outputs nothing.

## Environment

* deno v1.8.2

**Comment by kitsonk** [comment]
This isn't a defect, it is either a current design limitation and/or feature request, as we do not type inference (e.g. inferred return types, or in this case, object literals.  We only document specified type annotations.

**Comment by kitsonk** [comment]
Correction, we do infer some trivial types for const variables, just not more complex types like object literals.

**Comment by kitsonk** [comment]
As mentioned in #113, we should also ensure that when we infer types for an object literal, we infer the associated JSDoc block.

**Comment by crowlKats** [comment]
Closing as this is mostly supported now
