### ISSUE TITLE
Feature request: Support bare (import-mappable) module identifiers.

### ISSUE THREAD

**Issue by vovacodes** [denoland/deno_doc#93]
As an author of a browser-targetted library I would like to publish it as ESM with the dependency imports using bare module specifiers, e.g. `"react"`, so the users could specify the exact version that should be used with import maps.

Unfortunately, I cannot use https://doc.deno.land/ to generate my documentation because obviously, it doesn't know what should it resolve `"react"` to.

**Example:** 
```ts
import * as React from "react"

export function foo() {
  console.log({ React })
}
```
https://doc.deno.land/https/gist.githubusercontent.com/vovacodes/65c626be8aec4062feed0f7f38b852d4/raw/cdbb6daeb0a0e0fddeace63f61535a118541d6ab/uses-bare-specifier.ts

This issue is a question/discussion about how could we allow for such use-case?
Possible options:
 
1. Annotate the import with `// @deno-types="$path to the types file$"`
  - This can be quite tedious to maintain on the library side unless you use a "deps.ts" approach

2. Provide mapping through a query param: `https://doc.deno.land/https/../uses-bare-specifier.ts?importmap={"react": "$resolution URL$"}` 
  - The URLs can and will become too long, what can we do about that?
 
3. Provide a query parameter that points to an import map in the same host as the target module, something like: `?import-map=../import_map.json` (by @kitsonk)

I, personally, believe the second and/or third options are the best in terms of UX and I could try implementing it as a proposal but I'd love to hear the opinion of the others.

Cheers folks!

**Comment by kitsonk** [comment]
Or a 3rd option, the website supports the query parameter that points to an import map in the same host as target module, something like: `?import-map=../import_map.json`

**Comment by vovacodes** [comment]
I'd probably say we then should support both relative and absolute URL paths in the 3rd option.

**Comment by vovacodes** [comment]
I figured that this is a wrong repo for this issue, in fact, `deno doc` already supports import maps through the `--import-maps` flag, so I'm closing this. You can follow the future discussion and progress in https://github.com/denoland/doc_website/pull/173
